[build]
  publish = "."

[[redirects]]
  from = "/accesibilidad/*"
  to = "/contenido/accesibilidad/:splat"
  status = 200

[[redirects]]
  from = "/paginas/*"
  to = "/contenido/paginas/:splat"
  status = 200

[[redirects]]
  from = "/recursos/*"
  to = "/contenido/recursos/:splat"
  status = 200

[[redirects]]
  from = "/firma-tu-visita/*"
  to = "/contenido/firma-tu-visita/:splat"
  status = 200

[[redirects]]
  from = "/directorios/*"
  to = "/contenido/directorios/:splat"
  status = 200

[[redirects]]
  from = "/datos/*"
  to = "/contenido/datos/:splat"
  status = 200

[[headers]]
  for = "/estilos.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/main.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
